dal: Fix NUMA node deserialization
The List implementation returned by ResultSet#getArray causes
deserialization issues in GWT. The list can be serialized and used in
GWT but when deserializing it again in the backend this exception
occures:

    Exception while dispatching incoming RPC call:
        java.lang.NumberFormatException: For input string: "undefined"

To work around that the array in question is copied to a normal
ArrayList.

Change-Id: I5a32b219c091bb37c05b330547ddeeaa5c0e3d3a
Bug-Url: https://bugzilla.redhat.com/1350861
Signed-off-by: Roman Mohr <rmohr@redhat.com>
(cherry picked from commit d6b1ff0d512947285c72d669cc67b4ba51929739)