packaging: spec: missing dep on ovirt-host-deploy
Added missing dependency on ovirt-host-deploy
avoiding Internal error: cannot import name hardware
during upgrade if AIO is enabled.

Change-Id: Ic9835b126611b399aaeb7fdd263bf1935a4235f5
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>