packaging: spec: require jaxb-api
should resolve build error:

+ /usr/libexec/platform-python /usr/share/java-utils/mvn_artifact.py /home/jenkins/workspace/ovirt-engine_standard-check-patch/ovirt-engine/rpmbuild/BUILDROOT/ovirt-engine-4.5.0-0.2.master.20211203133347.git4c11a907d7f.el8.x86_64/usr/share/maven-poms/JPP.ovirt-engine-aaa.pom ovirt-engine/aaa.jar
xmvn-resolve failed:
Unhandled exception
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at org.fedoraproject.xmvn.tools.resolve.ResolverCli.parseRequests(ResolverCli.java:60)
	at org.fedoraproject.xmvn.tools.resolve.ResolverCli.run(ResolverCli.java:112)
	at org.fedoraproject.xmvn.tools.resolve.ResolverCli.main(ResolverCli.java:152)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

Change-Id: I77e37aeed809a0c98977da76b8ef9c97972162ed
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>