packaging: setup - postinstall: send content as binary false
As explained in [1], sending content as binary fails on python3/fc29:
File "/usr/lib/python3.6/site-packages/otopi/filetransaction.py", line 253, in prepare
   os.write(fd, self._content)
TypeError: a bytes-like object is required, not 'str'

[1] https://gerrit.ovirt.org/#/c/102089/4/packaging/setup/plugins/ovirt-engine-common/base/core/postinstall.py

Change-Id: I6bc26e6cb187dc02026fb8270b6f0512a5d8cb2a
Signed-off-by: Daniel Erez <derez@redhat.com>