core: re-support broken apache proxy
apache proxy support was broken in:
I37156061cbdd, 'core: i18n splash screen.'

The changed cause invalid redirection and the following error message in
console log:
---
Exception while dispatching incoming RPC call:
java.lang.SecurityException: Blocked request without GWT base path
header (XSRF attack?)
---

Content:

1. Remove unused ovirt-engine.html (what was index.html) as it is
   superseded by index.jsp

2. Remove redundant welcome directive from web.xml

3. Rename /index.jsp to /ovirt-engine.jsp to be referenced by both
   apache and jboss.

4. Rename servlet mapping of /index to /ovirt-engine.

5. Modify 404.html pages to redirect to /ovirt-engine instead of
   /ovirt-engine.html

6. Remove reference of ovirt-engine.html from the proxy.

Change-Id: I7ac8feb720d73f0b1107b0bf0908930c525ea542
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>