packaging: add http backend CA file option into default imageio config
If the use wants to use different CA for the oVirt engine and hosts
(e.g. if user generates own certificates for the engine), imageio
requests sent by proxy to dameon would fail with

    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]
    certificate verify failed: self signed certificate in certificate
    chain (_ssl.c:1108)

To mitigate this issue, option backend_http:ca_file was added into
imageio configuration. It allows to specify CA file to backend HTTP
service in case it's different from CA file configured in tls:ca_file.

Add this option into imageio config file on engine host, pointing to
engine CA file.

As this option was added in ovirt-imageio 2.0.10-1, we also require
this imageio version.

Change-Id: Ifcbb87dcef531df0762a34bc1e3fd9608e056461
Bug-Url: https://bugzilla.redhat.com/1866745
Related-To: https://bugzilla.redhat.com/1862107
Signed-off-by: Vojtech Juranek <vjuranek@redhat.com>