setup: Fix additional package list
The comma at the beginning of the 'DEFAULT_ADDITIONAL_PACKAGES' string
causes the deployment process to break, while looking for a package with
an empty name, i.e.:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/otopi/context.py", line 132, in _executeMethod
    method['method']()
  File "/usr/share/ovirt-engine/setup/bin/../plugins/ovirt-engine-setup/ovirt-engine-common/distro-rpm/packages.py", line 408, in _customization
    ) = self._checkForProductUpdate()
  File "/usr/share/ovirt-engine/setup/bin/../plugins/ovirt-engine-setup/ovirt-engine-common/distro-rpm/packages.py", line 237, in _checkForProductUpdate
    mpm.installUpdate(packages=entry['packages'])
  File "/usr/lib/python2.7/site-packages/otopi/miniyum.py", line 884, in installUpdate
    **kwargs
  File "/usr/lib/python2.7/site-packages/otopi/miniyum.py", line 500, in _queue
    package=package,
RuntimeError: Package  cannot be found

This is probably caused by a .split(',') done somewhere. Removing
the comma should fix this problem.

Change-Id: Ia1794b43cde9bea8020b1447095d91c785537812
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>