packaging: Reserve imageio ports
Recently we see random startup failures in OST:

2020-05-14 20:38:23,737 ERROR   (MainThread) [server] Server failed
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/ovirt_imageio/server.py", line 37, in main
    server = Server(cfg)
  File "/usr/lib64/python3.6/site-packages/ovirt_imageio/server.py", line 83, in __init__
    self.control_service = services.ControlService(self.config, self.auth)
  File "/usr/lib64/python3.6/site-packages/ovirt_imageio/services.py", line 148, in __init__
    self._server = http.Server(("localhost", port), http.Connection)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

So far we see only failures to bind imageio control port (54324), but in
the past we have seen also failures to bind imageio data port (54323).

The best way to avoid this issue is to reserve imageio ports so the
kernel will not assign them to any other process.

Change-Id: Ic20934babfbd14d8a85457ec874a7effdd85b823
Bug-Url: https://bugzilla.redhat.com/1517764
Signed-off-by: Nir Soffer <nsoffer@redhat.com>