core: Add missing javax.mail.api dependency
Adds missing javax.mail.api dependency to fix:

  NoClassDefFoundError: javax/mail/internet/AddressException

which is most probably caused by classloader differencies between
WildFly 8 and 10.

Change-Id: Ib98b6b0951c76d905a4674ec3ad2f60eafcf8422
Bug-Url: https://bugzilla.redhat.com/1326578
Signed-off-by: Martin Perina <mperina@redhat.com>