infra: exclude junit 3.8.1 transitive dependencies
When trying to run tests from intellij from bll module
fails with error:

Internal Error occurred.

org.junit.platform.commons.JUnitException: TestEngine
with ID 'junit-vintage' failed to discover tests

Caused by: org.junit.platform.commons.JUnitException:
Unsupported version of junit:junit: 3.8.1. Please upgrade to version 4.12 or later.

this patch excludes junit 3.8 transitive dependencies

Change-Id: I2a169f0a02c6e59b79459774b251e34569a4b0b5
Signed-off-by: Saif Abu Saleh <sabusale@redhat.com>