core: Fix search for templates on username
[search] Templates: Users.usrname = causes PSQLException:
ERROR: missing FROM-clause entry for table "vms"

This patch fixes this behavior

Change-Id: Ia3051c13fce1a7e1733624e078bad28fa7e0dfb7
Bug-Url: https://bugzilla.redhat.com/1187703
Signed-off-by: lzelkha@redhat.com <lzelkha@redhat.com>