frontend: Better message when using old GUI
When application is updated but an user still has the old GUI (user
portal or webadmin) loaded in the browser the following message will
appear in the log:

  Exception while dispatching incoming RPC call:
  com.google.gwt.user.client.rpc.SerializationException: Could not find
  ClientOracle data for permutation DA478849974581CCAF06E5E18D613907

This is not very friendly for the administrator looking at the log file.

This patch replaces that message with something that is hopefully more
useful for the administrator, something like this:

  Exception while dispatching incoming RPC call:
  com.google.gwt.user.client.rpc.SerializationException: Can't find the
  serialization policy file. This probably means that the user has an old
  version of the application loaded in the browser. To solve the issue the
  user needs to close the browser and open it again, so that the
  application is reloaded.

Change-Id: Id58f425d2745fdcba4bdfa8fa66a61e7e6e72d00
Bug-Url: https://bugzilla.redhat.com/909904
Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>