host-deploy: ssh: use apache commons Hex instead of j2se
although javax.xml.bind.DatatypeConverter is part of j2se[1], it is missing
from jboss rhev environment.

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at org.ovirt.engine.core.utils.ssh.SSHClient._validateDigest(SSHClient.java:97) [utils.jar:]
        at org.ovirt.engine.core.utils.ssh.SSHClient.sendFile(SSHClient.java:625) [utils.jar:]
        at org.ovirt.engine.core.utils.ssh.SSHDialog.sendFile(SSHDialog.java:361) [utils.jar:]

resolution is to use apache commons Hex to decode hex instead.

[1] http://docs.oracle.com/javase/7/docs/api/javax/xml/bind/DatatypeConverter.html#parseHexBinary%28java.lang.String%29

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=987891
Change-Id: Ie57b334d152da9e20ce556f801d48b836378fa7b
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>