Revert "core: Add SATA to hotpluggable interfaces"
This reverts commit d0455b1ad090fc625552d430eb7a88fb66468ee6.
It appears as this operation is not supported by the underlying platform:
libvirtError: Operation not supported: disk bus 'sata' cannot be hotplugged.
So it's better to block it at the engine level.

Change-Id: Ide6e8cb70a828f191f4669ffa420b46b2ba84e54
Bug-Url: https://bugzilla.redhat.com/1771469
Signed-off-by: Arik Hadas <ahadas@redhat.com>