engine-setup: Don't use engine FQDN in imageio
Using engine FQDN is the reason we see these failures during boot:

    OSError: [Errno 99] Cannot assign requested address

Looking in boot logs, we can see that systemd starts ovirt-imageio
before netowrk-online.target and the FQDN is available.

According to systemd wiki[1], we have 2 ways to mitigate this:

- Depend on network-online.target - this works, but may delay imageio up
  to 90 seconds if NetworkManager thinks that the network is not ready.

- Listen to one the pseudo-addresses ([::] or 0.0.0.0) which are
  unconditionally available regardless of network status.

Removing engine FQDN from ovirt-imageio engine configuration, since I
don't see a reason to listen only to one interface, and this complicates
setup and cause trouble.

[1] https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

Change-Id: I21065a702f38b3f81b19c079ecab259754779415
Signed-off-by: Nir Soffer <nsoffer@redhat.com>