webadmin: fix StorageForceCreatePopupView
The 'latch' initialization was removed from StorageForceCreatePopupView
as part of change If582ca8baf550336918ce337663daab3ee444aec
Adding it back as it causing an excpetion[1] when trying to open
the confirm window.

[1]
SEVERE: Uncaught exception
com.google.gwt.core.client.JavaScriptException: (TypeError) :
 Cannot read property 'asEditor__Lorg_ovirt_engine_ui_common_widget_editor_WidgetWithLabelEditor_2' of undefined

Change-Id: I5dd09aec65c30b5e60677bee7c58347e353c337d
Signed-off-by: Daniel Erez <derez@redhat.com>