db: fix upgrade for app mode to roles
Role UserTemplateBasedVm was missing from the update list always
triggering the following error:

ERROR:  column "app_mode" contains null values

Change-Id: Ic5ebbba79deb6de091d27621196f361fd4fd3caf
Signed-off-by: Federico Simoncelli <fsimonce@redhat.com>