packaging: spec: use system jars
PACKAGE                      POM              FC19         EL6

apache-commons-compress      1.4.1            1.5-1        N/A
apache-commons-configuration 1.6              1.9-4        N/A
postgresql-jdbc              9.1-901-1.jdbc4  9.2.1002-2   8.4.701-8(*)
spring-asm                   3.1.1            N/A          N/A
objectweb-asm                N/A              3.3.1-7      N/A

apache-commons-jxpath        1.3              1.3-15       N/A
apache-mina                  2.0.1            2.0.4-6      N/A
apache-sshd                  0.7.0            0.7.0-3      N/A
jakarta-commons-httpclient   3.1              3.1-13       N/A
quartz                       2.1.2            2.1.2-7      N/A
spring-ldap                  1.3.1            1.3.1-5      N/A
springframework-*            1.3.1            1.3.1        N/A
ws-commons-util              1.0.2            1.0.1-26     1.0.1-13
xmlrpc-client                3.1.3            3.1.3-5      N/A

(*) too low.

objectweb-asm is used instead of spring-asm, without we get the following at server.log:

Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.<init>(AbstractAutowireCapableBeanFactory.java:121)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.<init>(DefaultListableBeanFactory.java:150)
        at org.springframework.jdbc.support.SQLErrorCodesFactory.<init>(SQLErrorCodesFactory.java:103)
        at org.springframework.jdbc.support.SQLErrorCodesFactory.<clinit>(SQLErrorCodesFactory.java:68)
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:141)
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:104)
        at org.ovirt.engine.core.dal.dbbroker.CustomSQLErrorCodeSQLExceptionTranslator.<init>(CustomSQLErrorCodeSQLExceptionTranslator.java:10)

Change-Id: I97995665ce34aeb2dd24d69b96919999d5498f43
Signed-off-by: Alon Bar-Lev <alonbl@redhat.com>