core: elect a new master storage domain if there's no master
Currently, starting the engine with no storage domain selected as a
master storage domain causes the engine to be in an infinite loop,
trying to get the master storage domain for the storage pool [1].
This patch elects a data storage domain and reconstructs the storage
pool when such a case occurs.

[1]
IrsBroker::Failed::GetStoragePoolInfoVDS: IRSGenericException:
IRSErrorException: IRSNoMasterDomainException: Cannot find master domain: 'spUUID=332dd4e0-9a94-4867-8685-7be646cddd7c, msdUUID=00000000-0000-0000-0000-000000000000'

Change-Id: I82cb4476b52a6ee936b3ed2f22d34dcbdd36a9a6
Bug-Url: https://bugzilla.redhat.com/1879032
Signed-off-by: Shani Leviim <sleviim@redhat.com>