Revert "core: Mixing Q35 with Legacy Bios fails VM launch"
Commit 6b1d1e3099879d6991401dd545338f7a856fc426 breaks AddClusterCommand
for kubevirt provider with following message:

ERROR: null value in column "bios_type" violates not-null constraint

Change-Id: I80bd8e70c2b44524fc41df79866e72038568ab27
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>